### ISSUE TITLE
issues with SQL Superset query

### ISSUE THREAD

**Issue by acivitillo** [dyvenia/timeflow#301]
- [ ] The billing value is not calculated  correctly
- [ ] The rate 400 is incorrect for the month of May, it should start from month 7

![image](https://user-images.githubusercontent.com/54931660/168252033-be9c5470-8f8c-49eb-a258-fa3fc9f44e9b.png)

![image](https://user-images.githubusercontent.com/54931660/168252298-b6131b56-6114-4452-8e30-3c64177f7538.png)

**Comment by krzyzanowskik** [comment]
Hey Jedrzej
--
Please find below my fixes.
In order to have the correct rate for the correct month I have added three steps:

- add the **rate_valid_from_month** from rate table by extracting the month from **'valid_from'** column
- making a where condition that we are taking the **month** column higher or equal to **rate_valid_from_month** column 
- adding to the condition the **OR** clause that rate can be **NULL** ( for instance dyvenia time )

Timelog table:
-
```sql
SELECT
    app_db.appuser.username as username,
    app_db.client.name as client_name,
    app_db.epic.short_name as epic_name,
    app_db.timelog.year as year,
    app_db.timelog.month as month,
    app_db.rate.amount as rate_amount,
    EXTRACT(MONTH FROM valid_from )  as rate_valid_from_month,
    SUM(timelog.count_days) as timelog_count_days,
    0 AS forecast_days,
    SUM(timelog.count_days) * app_db.rate.amount as billings,
    0 AS est_billings
FROM app_db.timelog
    LEFT JOIN app_db.epic ON timelog.epic_id = epic.id
    LEFT JOIN app_db.sponsor ON epic.sponsor_id = sponsor.id
    LEFT JOIN app_db.client ON sponsor.client_id = client.id
    LEFT JOIN app_db.appuser ON app_db.timelog.user_id = app_db.appuser.id
    LEFT JOIN app_db.rate ON client.id = rate.client_id and appuser.id = rate.user_id

WHERE month>=EXTRACT(MONTH FROM valid_from ) OR app_db.rate.amount ISNULL

GROUP BY username, client_name, epic_name, year, month, rate_amount, valid_from
```

Forecast table:
-
```sql
SELECT
    app_db.appuser.username as username,
    app_db.client.name as client_name,
    app_db.epic.short_name as epic_name,
    app_db.forecast.year as year,
    app_db.forecast.month as month,
    app_db.rate.amount as rate_amount,
    EXTRACT(MONTH FROM valid_from )  as rate_valid_from_month,
    0 AS timelog_count_days,
    app_db.forecast.days as forecast_days,
    0 AS billings,
    app_db.rate.amount * app_db.forecast.days AS est_billings
FROM app_db.forecast
    LEFT JOIN app_db.epic ON app_db.forecast.epic_id = app_db.epic.id
    LEFT JOIN app_db.sponsor ON app_db.epic.sponsor_id = app_db.sponsor.id
    LEFT JOIN app_db.client ON app_db.sponsor.client_id = app_db.client.id
    LEFT JOIN app_db.appuser ON app_db.forecast.user_id = app_db.appuser.id
    LEFT JOIN app_db.rate ON app_db.client.id = app_db.rate.client_id AND app_db.appuser.id = app_db.rate.user_id
WHERE month>=EXTRACT(MONTH FROM valid_from ) OR app_db.rate.amount ISNULL
```

**NOTE:**
Fore Forecast table you may consider to do as well the  **app_db.rate.amount * SUM(forecast.days) AS est_billings** 

Please try these solutions, and let me know if there is anything I can help with!
Best regards,
Kamil

**Comment by liberty-rising** [comment]
@acivitillo As for the second issue with the query, I've noticed that the data says that the rate is supposed to be active from May, not from July. Perhaps this is a data error?

![image](https://user-images.githubusercontent.com/93674695/169545976-538d43ec-2739-4a6c-b141-929df23f19aa.png)
